### ISSUE TITLE
Preallocate memory

### ISSUE THREAD

**Issue by ahoarau** [asherikov/qpmad#5]
Hello,
I understand that you can predefine the problem with template parameters to avoid allocations, but can you preallocate data at runtime ?

Something like:

```
Solver solver;
solver.preallocate(size, n_ctrs); <<< allocations

solver.solve() <<<< no alloc

```

best,

**Comment by asherikov** [comment]
Hi, there is no such functionality. It can be implemented, but I dont think it is useful.

- Have you actually performed any tests to make sure that this is an issue? `qpmad` does not explicitly release memory, so I would expect Eigen and standard library to handle resizes efficiently, i.e., without unnecessary reallocations.

- May be you are assuming that by performing allocations externally you can guarantee certain computation time in a control loop? This is not possible due to the nature of QP problems (there are exceptions, but I doubt they are relevant in your case).

- If you are dealing with several problems of different sizes you can use multiple instances of the solver.

**Comment by ahoarau** [comment]
Mostly option 1 and 2. 

1. Dynamic allocations are an actual issue for my use case. 
2. Ideally a max_iter (for max iterations) could by passed, qpoases's style, to bound the computation time.

In my usecase, the size of the problem is determined by some config file, not known at compile time. Then is it fixed for the lifetime of the application - very common on robotics.

Basically I'm trying to replicate qpoases fonctionalities : init, hotstart, and max_iter.

**Comment by asherikov** [comment]
1. Ok, I'll keep this in mind, but I cannot promise anything any time soon. It would be helpful if you can provide a benchmark.
2. Number of iterations can be limited https://github.com/asherikov/qpmad/blob/master/include/qpmad/solver_parameters.h#L47

**Comment by ahoarau** [comment]
Excellent. I thought at first that I needed to call **once** `solver.solve()` in order to allocate everything necessary, and then all the following calls would be allocation-free.

**Comment by ahoarau** [comment]
Hello @asherikov . Any news on this ?

**Comment by asherikov** [comment]
no, if you are willing to support development drop me an email

**Comment by asherikov** [comment]
I've implemented `reserve()` method for memory preallocation, it is now available in the master branch, e.g., https://github.com/asherikov/qpmad/blob/master/test/preallocation.cpp#L41. If you find any bugs pls open a new issue.
